### ISSUE TITLE
Prepare new release?

### ISSUE THREAD

**Issue by jtheoof** [mattn/open-vim#8]
A few cool new features have been added, especially the settings configuration for the executable path.

Could you kindly release a new version @mattn ?

**Comment by mattn** [comment]
I don't use atom no longer(uses vscode), so please wait to publish. I'll do it in few days. Sorry.

**Comment by jtheoof** [comment]
I wouldn't mind taking over the ownership of the package if you feel it's too much of a hassle.

**Comment by mattn** [comment]
Thanks. I looked disscus-forum to find change ownership of atom packages, But not found. I released v0.2.3 just now.
